# name: Deploy to Lambda with Zappa

# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1
#       - name: Set up Python 3.7
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.7

#       - name: Install venv
#         run: |
#           python -m venv venv

#       - name: Install requirements
#         env:
#           VIRTUAL_ENV: ./venv
#         run: |
#           source venv/bin/activate
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Configure AWS profile
#         env:
#           VIRTUAL_ENV: ./venv
#         run: |
#           source venv/bin/activate
#           aws configure set region ap-northeast-2 --profile default
#           aws configure set output json --profile default
#           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
#           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default

#       - name: Deploy with zappa
#         env:
#           VIRTUAL_ENV: ./venv
#         run: |
#           source venv/bin/activate
#           zappa update dev
